using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Crabshell.SourceGenerator;

[Generator]
public class CrabshellDbContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dummySource = """
                          // <auto-generated />
                          namespace Crabshell.Data;
                          public class CrabshellDbDummy {}
                          """;
        context.RegisterPostInitializationOutput(i => i.AddSource("CrabshellDbDummy.g.cs", SourceText.From(dummySource, Encoding.UTF8)));

        var collectionClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c 
                                               && c.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (symbol is null) return null;

                    foreach (var attr in symbol.GetAttributes())
                    {
                        if (attr.AttributeClass?.Name == "CollectionAttribute" || 
                            attr.AttributeClass?.ToDisplayString() == "Crabshell.Core.Attributes.CollectionAttribute")
                        {
                            return new CollectionInfo(
                                symbol.Name,
                                symbol.ContainingNamespace.ToDisplayString(),
                                ctx.SemanticModel.Compilation.AssemblyName ?? "Unknown");
                        }
                    }

                    return null;
                }
            )
            .Where(static c => c is not null);

        var collected = collectionClasses.Collect();

        context.RegisterSourceOutput(collected, static (ctx, collections) =>
        {
            var valid = collections
                .Where(x => x is not null)
                .Select(x => x!)
                .ToList();

            var groups = valid.GroupBy(x => x.AssemblyName);

            foreach (var group in groups)
            {
                var assemblyName = group.Key;
                var assemblyCollections = group.ToList();

                var usings = assemblyCollections
                    .Select(c => $"using {c.Namespace};")
                    .Distinct()
                    .OrderBy(u => u);

                var crabshellDbSets = assemblyCollections
                    .Select(c => $"    public DbSet<{c.ClassName}> {Pluralize(c.ClassName)} => _db.Set<{c.ClassName}>();");

                var dbContextSource = $$"""
                                        // <auto-generated />
                                        using Microsoft.EntityFrameworkCore;
                                        using Crabshell.Data;
                                        {{string.Join("\n", usings)}}

                                        namespace Crabshell.Data;

                                        public class CrabshellDb
                                        {
                                            private readonly CrabshellDbContext _db;

                                            public CrabshellDb(CrabshellDbContext db) => _db = db;

                                        {{string.Join("\n", crabshellDbSets)}}
                                        }
                                        """;

                ctx.AddSource($"CrabshellDb.{assemblyName}.g.cs", SourceText.From(dbContextSource, Encoding.UTF8));
            }
        });
    }
    private static string Pluralize(string name) =>
        name.EndsWith("s") ? name : name + "s";
    private record CollectionInfo(string ClassName, string Namespace, string AssemblyName);
}

