using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Crabshell.SourceGenerator;

[Generator]
public class CrabshellDbContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dummySource = """
                          // <auto-generated />
                          namespace Crabshell.Data;
                          public class CrabshellDbDummy {}
                          """;
        context.RegisterPostInitializationOutput(i => i.AddSource("CrabshellDbDummy.g.cs", SourceText.From(dummySource, Encoding.UTF8)));

        var collectionClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Crabshell.Core.Attributes.CollectionAttribute",
                predicate: static (node,  _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return new CollectionInfo(
                        symbol.Name,
                        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        ctx.SemanticModel.Compilation.AssemblyName ?? "Unknown");
                }
            );

        var collected = collectionClasses.Collect();

        context.RegisterSourceOutput(collected, static (ctx, collections) =>
        {
            var valid = collections.ToList();

            var groups = valid.GroupBy(x => x.AssemblyName);

            foreach (var group in groups)
            {
                var assemblyName = group.Key;
                var assemblyCollections = group.ToList();

                var crabshellDbSets = assemblyCollections
                    .Select(c => $"    public global::Microsoft.EntityFrameworkCore.DbSet<{c.FullyQualifiedName}> {Pluralize(c.ClassName)} => _db.Set<{c.FullyQualifiedName}>();");

                var dbContextSource = $$"""
                                        // <auto-generated />
                                        namespace Crabshell.Data;

                                        public class CrabshellDb
                                        {
                                            private readonly global::Crabshell.Data.CrabshellDbContext _db;

                                            public CrabshellDb(global::Crabshell.Data.CrabshellDbContext db) => _db = db;

                                        {{string.Join("\n", crabshellDbSets)}}
                                        }
                                        """;

                ctx.AddSource($"CrabshellDb.{assemblyName}.g.cs", SourceText.From(dbContextSource, Encoding.UTF8));
            }
        });
    }
    private static string Pluralize(string name) =>
        name.EndsWith("s") ? name :
        name.EndsWith("y") ? name.Substring(0, name.Length - 1) + "ies" :
        name + "s";
    
    private record CollectionInfo(string ClassName, string FullyQualifiedName, string AssemblyName);
}

